plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

base.archivesName = 'ShaderPatcher-Fabric 1.19'
java.toolchain.languageVersion = JavaLanguageVersion.of("${java_version}")

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${api_version}"

    implementation project(path: ':common')

    include 'org.snakeyaml:snakeyaml-engine:2.6'
}

jar {
    from project(':common').sourceSets.main.output
}

processResources {
    def version = rootProject.version
    def java_version_range = project.java_version_range
    def minecraft_version_range = project.minecraft_version_range
    def loader_version_range = project.loader_version_range

    inputs.property "version", version
    inputs.property "java_version_range", java_version_range
    inputs.property "minecraft_version_range", minecraft_version_range
    inputs.property "loader_version_range", loader_version_range

    filesMatching("fabric.mod.json") {
        expand(
                "version": version,
                "java_version_range": java_version_range,
                "minecraft_version_range": minecraft_version_range,
                "loader_version_range": loader_version_range
        )
    }
}