pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }

        maven {
            name = "Forge"
            url = "https://maven.minecraftforge.net/"
        }

        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "ShaderPatcher"

include("common")

include(":fabric:119")
include(":fabric:261")

include(":forge:119")