plugins {
    id 'net.minecraftforge.gradle'
    id 'maven-publish'
}

base {
    archivesName = "ShaderPatcher-forge"
}

jarJar.enable()

minecraft {
    mappings channel: 'official', version: '1.19'
}

dependencies {
    minecraft "net.minecraftforge:forge:1.19-41.1.0"

    implementation project(":common")

    jarJar("org.snakeyaml:snakeyaml-engine:[2.9,2.10)") {
        jarJar.pin(it, '2.9')
    }
}

sourceSets {
    main {
        output.dir(project(":common").sourceSets.main.output)
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named('processResources', ProcessResources).configure {
    inputs.property('version', project.version)

    filesMatching('META-INF/mods.toml') {
        expand(version: project.version)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

tasks.named("compileJava") {
    dependsOn(project(":common").tasks.named("classes"))
}

tasks.named("build") {
    dependsOn("reobfJarJar")
}