plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

base {
    archivesName = "ShaderPatcher-forge-1.19"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', 'shaderpatcher'

            mods {
                shaderpatcher {
                    source sourceSets.main
                }
            }
        }

        register('client')

        register('server') {
            args '--nogui'
        }

        register('gameTestServer')

        register('data') {
            workingDir = layout.projectDirectory.dir('run-data')

            args '--mod', 'shaderpatcher',
                    '--all',
                    '--output', layout.projectDirectory.dir('src/generated/resources'),
                    '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }

    mappings channel: 'official', version: minecraft_version
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency(
            "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    )

    implementation project(":common")

    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.5'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

jar {
    from(project(":common").sourceSets.main.output)

    def projectName = project.name

    inputs.property "projectName", projectName

    from(rootProject.file("LICENSE")) {
        rename { "${it}_${projectName}" }
    }
}