modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/Excederus/ShaderPatcher/issues/"

[[mods]]
modId="shaderpatcher"
version="${mod_version}"
displayName="Shader Patcher"
displayURL="https://github.com/Excederus/ShaderPatcher/"
logoFile="assets/shaderpatcher/icon.png"
authors="Excederus"
description='''
Attempts to add mod support to any shaderpack
'''

[[dependencies.shaderpatcher]] #optional
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.shaderpatcher]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"